databases:
  - name: creamydelight-db
    plan: free
    databaseName: creamydelight
    user: creamydelight_user

services:
  - type: web
    name: creamydelight
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        fromDatabase:
          name: creamydelight-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
